name: metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-readme-metrics:
    name: Update GitHub Readme with Metrics
    runs-on: ubuntu-latest
    environment:
      name: Production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
